apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: wordpress
  labels:
    app: wordpress
    tier: mysql
spec:
  ##
  # Create label selectors here
  ##
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_ROOT_PASSWORD
          value: supers3cr3t
        ports:
        - containerPort: 3306
          name: mysql
        ##
        # create resource limits here
        ##
    ##
    # define volume mounts here, be sure to reference
    # the PVC in your container spec
    ##
---
##
# Create persistant volume claim in this file
##